### ISSUE TITLE
Problèmes d'authentification

### ISSUE THREAD

**Issue by FabienSanchez** [AmandineCr/module-test-puppeteer#1]
### Reproduire le bug :
Navigateur : Firefox Quantum 62.0.3 (64 bits)

1. Charger [Polr du campus](http://polr.campus-grenoble.fr/)
2. Cliquer sur "Sign Up"
3. Remplir les 3 champs du formulaire avec : 
    * Username : bug%
    * Password : bug%
    * Email : bug@bug.bug
4. Tester la  [connexion](http://polr.campus-grenoble.fr/login) avec ce compte
5. Constater le message d'erreur : ````Error Invalid password or inactivated account. Try again.````

--------------

C'est probablement les charactères spéciaux dans le nom d'utilisateur qui provoquent ce bug

**Comment by AmandineCr** [comment]
Merci pour votre feedback, en effet le problème venait de chez nous, il est maintenant résolu. Vous pouvez maintenant vous connecter avec % dans votre nom d'utilisateur.
